// Auto-generated by Week 4 AI/ML Mote Lab — do not edit manually.
// These normalization parameters must exactly match the Python StandardScaler used during training.
// If you retrain with new data, regenerate this file.

#pragma once

const int   NUM_FEATURES        = 4;
const float FEATURE_MEAN[4] = { 0.81616195f, 0.56829437f, 1.00499091f, 2.44983333f };
const float FEATURE_STD[4]  = { 0.25958720f, 0.17012908f, 0.27459333f, 0.71879958f };
